version: '3.1'

services:
  db:
    image: postgres:15
    container_name: product-catalog
    restart: always
    environment:
      POSTGRES_DB: product_catalog_db
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
